export const REPO_PROJECTS: Record<string, {
  description: string;
  project: string;
  client: string;
  lang: string;
  branch: string;
  url: string;
}> = {
  "onGuard-AI-alfred": {
    description: "AI-powered Alfred assistant for OnGuard",
    project: "OnGuard",
    client: "Netsweeper",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/onGuard-AI-alfred",
  },
  "onGuard-AI-AlfredModel": {
    description: "Alfred ML model training and inference",
    project: "OnGuard",
    client: "Netsweeper",
    lang: "Python",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/onGuard-AI-AlfredModel",
  },
  "onGuard-AI-Runner": {
    description: "AI job runner and scheduler",
    project: "OnGuard",
    client: "Netsweeper",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/onGuard-AI-Runner",
  },
  "onGuard-DataExplorer": {
    description: "Data exploration and visualization dashboard",
    project: "OnGuard",
    client: "Netsweeper",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/onGuard-DataExplorer",
  },
  "onguard-infra-monorepo": {
    description: "Infrastructure monorepo for OnGuard services",
    project: "OnGuard",
    client: "Netsweeper",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/onguard-infra-monorepo",
  },
  "onguard-infra-web": {
    description: "Web infrastructure and deployment",
    project: "OnGuard",
    client: "Netsweeper",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/onguard-infra-web",
  },
  "onguard-infra-runner_old": {
    description: "Legacy runner infrastructure",
    project: "OnGuard",
    client: "Netsweeper",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/onguard-infra-runner_old",
  },
  "onguard-infra-db": {
    description: "Database infrastructure and migrations",
    project: "OnGuard",
    client: "Netsweeper",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/onguard-infra-db",
  },
  "PAM-infra-monorepo": {
    description: "PAM infrastructure monorepo",
    project: "PAM",
    client: "Netcore",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/PAM-infra-monorepo",
  },
  "PAM-Runner": {
    description: "PAM job runner",
    project: "PAM",
    client: "Netcore",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/PAM-Runner",
  },
  "PAM-infra-runner": {
    description: "PAM runner infrastructure",
    project: "PAM",
    client: "Netcore",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/PAM-infra-runner",
  },
  "PAM-infra-web": {
    description: "PAM web infrastructure",
    project: "PAM",
    client: "Netcore",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/PAM-infra-web",
  },
  "PAM-Web": {
    description: "PAM web application",
    project: "PAM",
    client: "Netcore",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/PAM-Web",
  },
  "COACH-Runner": {
    description: "COACH job runner",
    project: "COACH",
    client: "Zazi Play",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/COACH-Runner",
  },
  "COACH-Web": {
    description: "COACH web application",
    project: "COACH",
    client: "Zazi Play",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/COACH-Web",
  },
  "COACH-infra-runner": {
    description: "COACH runner infrastructure",
    project: "COACH",
    client: "Zazi Play",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/COACH-infra-runner",
  },
  "COACH-infra-web": {
    description: "COACH web infrastructure",
    project: "COACH",
    client: "Zazi Play",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/COACH-infra-web",
  },
  "COACH-infra-monorepo": {
    description: "COACH infrastructure monorepo",
    project: "COACH",
    client: "Zazi Play",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/COACH-infra-monorepo",
  },
  "coachAIV2": {
    description: "COACH AI version 2",
    project: "COACH",
    client: "Zazi Play",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/coachAIV2",
  },
  "coachAI": {
    description: "COACH AI main repository",
    project: "COACH",
    client: "Zazi Play",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/coachAI",
  },
  "7colours_website": {
    description: "7Colours e-commerce website",
    project: "7Colours",
    client: "7Colours",
    lang: "PHP",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/7colours_website",
  },
  "woolsapp": {
    description: "WoolsApp mobile application",
    project: "WoolsApp",
    client: "Woolooloo",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/woolsapp",
  },
  "woolooloo_os": {
    description: "Woolooloo AI Operating System",
    project: "Woolooloo OS",
    client: "Woolooloo",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/woolooloo_os",
  },
  "website": {
    description: "Woolooloo marketing website",
    project: "Woolooloo OS",
    client: "Woolooloo",
    lang: "TypeScript",
    branch: "main",
    url: "https://github.com/The-Woolooloo-Company/website",
  },
};
